# Preparing the gold layer for the sales

In [1]:
import pandas as pd

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 3, Finished, Available, Finished, False)

In [2]:
df_spark = spark.table("silver.sales")

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 4, Finished, Available, Finished, False)

In [3]:
df_spark.printSchema()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 5, Finished, Available, Finished, False)

root
 |-- Brand: string (nullable = true)
 |-- Category: string (nullable = true)
 |-- City: string (nullable = true)
 |-- Continent: string (nullable = true)
 |-- CountryRegion: string (nullable = true)
 |-- Customer_Code: long (nullable = true)
 |-- CustomerKey: long (nullable = true)
 |-- Education: string (nullable = true)
 |-- Name: string (nullable = true)
 |-- Net_Price: double (nullable = true)
 |-- Occupation: string (nullable = true)
 |-- OrderDate: timestamp (nullable = true)
 |-- Product_Name: string (nullable = true)
 |-- ProductKey: long (nullable = true)
 |-- Quantity: long (nullable = true)
 |-- State: string (nullable = true)
 |-- Subcategory: string (nullable = true)
 |-- TotalRevenue: double (nullable = true)

In [4]:
df=df_spark.toPandas()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 6, Finished, Available, Finished, False)

In [5]:
df.info()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 7, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80238 entries, 0 to 80237
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Brand          80238 non-null  object
 1   Category       80238 non-null  object
 2   City           80238 non-null  object
 3   Continent      80238 non-null  object
 4   CountryRegion  80238 non-null  object
 5   Customer_Code  80238 non-null  int64
 6   CustomerKey    80238 non-null  int64
 7   Education      80238 non-null  object
 8   Name           80238 non-null  object
 9   Net_Price      80238 non-null  float64
 10  Occupation     80238 non-null  object
 11  OrderDate      80238 non-null  datetime64[us]
 12  Product_Name   80238 non-null  object
 13  ProductKey     80238 non-null  int64
 14  Quantity       80238 non-null  int64
 15  State          80238 non-null  object
 16  Subcategory    80238 non-null  object
 17  TotalRevenue   80238 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(4), object(11)
memory usage: 11.0+ MB

# Normalization

In [6]:
# Creating dim_customers

dim_customers = df[['Customer_Code','CustomerKey','Name','Education','Occupation' ]].drop_duplicates()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 8, Finished, Available, Finished, False)

In [7]:
dim_customers.head()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 9, Finished, Available, Finished, False)

,Customer_Code,CustomerKey,Name,Education,Occupation
0,797,18890,Customer_797,Unknown,Unknown
7,833,18924,Customer_833,Unknown,Unknown
8,14772,3773,"Torres, Stacy",Bachelors,Clerical
9,19333,8334,"Malhotra, Candace",Bachelors,Skilled Manual
10,19345,8346,"Prasad, Kaitlin",Partial College,Clerical

In [8]:
# Creating dim_geography


dim_geography= df[['City', 'State', 'CountryRegion', 'Continent']].drop_duplicates().reset_index(drop=True)
dim_geography['GeographyKey'] = dim_geography.index + 1

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 10, Finished, Available, Finished, False)

In [9]:
dim_geography.head()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 11, Finished, Available, Finished, False)

             City         State  CountryRegion      Continent  GeographyKey
0         Bayonne    New Jersey  United States  North America             1
1  Fredericksburg      Virginia  United States  North America             2
2       Frankfurt         Hesse        Germany         Europe             3
3          Kassel         Hesse        Germany         Europe             4
4       Brunswick  Lower Saxony        Germany         Europe             5

In [10]:
# Creating dim_product

dim_product = df[['ProductKey', 'Product_Name', 'Brand', 'Category', 'Subcategory']].drop_duplicates()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 12, Finished, Available, Finished, False)

In [11]:
dim_product.head()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 13, Finished, Available, Finished, False)

,ProductKey,Product_Name,Brand,Category,Subcategory
0,2351,Contoso Air conditioner 8000BTU M0320 White,Contoso,Home Appliances,Air Conditioners
1,1306,Contoso Lens Adapter M450 Black,Contoso,Cameras and camcorders,Cameras & Camcorders Accessories
2,449,WWI Desktop PC3.0 M0300 Black,Wide World Importers,Computers,Desktops
3,1549,The Phone Company PDA Handheld 4.7 inch L650 S...,The Phone Company,Cell phones,Smart phones & PDAs
4,2371,Contoso Air conditioner 10000BTU M0490 Grey,Contoso,Home Appliances,Air Conditioners

In [12]:
df = df.merge(dim_geography, on=['City', 'State', 'CountryRegion', 'Continent'], how='left')

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 14, Finished, Available, Finished, False)

In [13]:
df.shape

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 15, Finished, Available, Finished, False)

(80238, 19)

In [14]:
df.head()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 16, Finished, Available, Finished, False)

,Brand,Category,City,Continent,CountryRegion,Customer_Code,CustomerKey,Education,Name,Net_Price,Occupation,OrderDate,Product_Name,ProductKey,Quantity,State,Subcategory,TotalRevenue,GeographyKey
0,Contoso,Home Appliances,Bayonne,North America,United States,797,18890,Unknown,Customer_797,319.99,Unknown,2008-11-25,Contoso Air conditioner 8000BTU M0320 White,2351,2,New Jersey,Air Conditioners,639.98,1
1,Contoso,Cameras and camcorders,Bayonne,North America,United States,797,18890,Unknown,Customer_797,54.40,Unknown,2008-11-25,Contoso Lens Adapter M450 Black,1306,2,New Jersey,Cameras & Camcorders Accessories,108.80,1
2,Wide World Importers,Computers,Bayonne,North America,United States,797,18890,Unknown,Customer_797,279.20,Unknown,2008-11-25,WWI Desktop PC3.0 M0300 Black,449,2,New Jersey,Desktops,558.40,1
3,The Phone Company,Cell phones,Bayonne,North America,United States,797,18890,Unknown,Customer_797,311.20,Unknown,2008-11-25,The Phone Company PDA Handheld 4.7 inch L650 S...,1549,2,New Jersey,Smart phones & PDAs,622.40,1
4,Contoso,Home Appliances,Bayonne,North America,United States,797,18890,Unknown,Customer_797,343.99,Unknown,2008-11-25,Contoso Air conditioner 10000BTU M0490 Grey,2371,2,New Jersey,Air Conditioners,687.98,1

In [15]:
fact_sales= df[['CustomerKey', 'ProductKey', 'GeographyKey', 
                 'OrderDate', 'Quantity', 'Net_Price', 'TotalRevenue']]

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 17, Finished, Available, Finished, False)

In [16]:
fact_sales['DateKey'] = pd.to_datetime(
    fact_sales['OrderDate'],
    errors='coerce'
).dt.strftime('%Y%m%d')

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 18, Finished, Available, Finished, False)

/tmp/ipykernel_5870/1409572519.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fact_sales['DateKey'] = pd.to_datetime(

In [17]:
fact_sales['DateKey'] = fact_sales['DateKey'].astype(int)

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 19, Finished, Available, Finished, False)

/tmp/ipykernel_5870/439556063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fact_sales['DateKey'] = fact_sales['DateKey'].astype(int)

In [18]:
fact_sales.head()

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 20, Finished, Available, Finished, False)

,CustomerKey,ProductKey,GeographyKey,OrderDate,Quantity,Net_Price,TotalRevenue,DateKey
0,18890,2351,1,2008-11-25,2,319.99,639.98,20081125
1,18890,1306,1,2008-11-25,2,54.40,108.80,20081125
2,18890,449,1,2008-11-25,2,279.20,558.40,20081125
3,18890,1549,1,2008-11-25,2,311.20,622.40,20081125
4,18890,2371,1,2008-11-25,2,343.99,687.98,20081125

# Saving the Facts and Dims in the gold layer

In [19]:
spark_fact_sales = spark.createDataFrame(fact_sales)
spark_dim_geography = spark.createDataFrame(dim_geography)
spark_dim_product = spark.createDataFrame(dim_product)
spark_dim_customers = spark.createDataFrame(dim_customers)

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 21, Finished, Available, Finished, False)

In [20]:
spark_fact_sales.write.mode('overwrite').format("delta").saveAsTable("gold.fact_sales")
spark_dim_geography.write.mode('overwrite').format("delta").saveAsTable("gold.dim_geography")
spark_dim_product.write.mode('overwrite').format("delta").saveAsTable("gold.dim_product")
spark_dim_customers.write.mode('overwrite').format("delta").saveAsTable("gold.dim_customers")

StatementMeta(, ff2b8b6e-4be1-42af-8110-d173e2d32d03, 22, Finished, Available, Finished, False)