# Preparing the Silver layer for sales

In [1]:
import pandas as pd

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 3, Finished, Available, Finished, False)

In [2]:
df_spark=spark.table("bronze.sales")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 4, Finished, Available, Finished, False)

In [3]:
df=df_spark.toPandas()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 5, Finished, Available, Finished, False)

# EDA

In [4]:
df.head()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 6, Finished, Available, Finished, False)

,Brand,Category,City,Color,Continent,CountryRegion,Customer_Code,CustomerKey,Education,Name,Net_Price,Occupation,OrderDate,Product_Name,ProductKey,Quantity,State,Subcategory
0,Contoso,Cell phones,Spokane,Cell phones Accessories,North America,United States,CS551,18813,None,None,23.7405,None,1/1/2008,Cigarette Lighter Adapter for Contoso Phones E...,2492,1,Washington,Cell phones Accessories
1,Contoso,Cell phones,Spokane,Cell phones Accessories,North America,United States,CS551,18813,None,None,23.7405,None,1/1/2008,Cigarette Lighter Adapter for Contoso Phones E...,2492,1,Washington,Cell phones Accessories
2,Contoso,Cell phones,Spokane,Cell phones Accessories,North America,United States,CS551,18813,None,None,23.7405,None,1/1/2008,Cigarette Lighter Adapter for Contoso Phones E...,2492,1,Washington,Cell phones Accessories
3,Contoso,Cell phones,Spokane,Cell phones Accessories,North America,United States,CS551,18813,None,None,23.7405,None,1/1/2008,Cigarette Lighter Adapter for Contoso Phones E...,2492,1,Washington,Cell phones Accessories
4,Contoso,Cell phones,Spokane,Cell phones Accessories,North America,United States,CS551,18813,None,None,23.7405,None,1/1/2008,Cigarette Lighter Adapter for Contoso Phones E...,2492,1,Washington,Cell phones Accessories

In [5]:
df.info()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 7, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 298246 entries, 0 to 298245
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Brand          298246 non-null  object
 1   Category       298246 non-null  object
 2   City           298246 non-null  object
 3   Color          298246 non-null  object
 4   Continent      298246 non-null  object
 5   CountryRegion  298246 non-null  object
 6   Customer_Code  298246 non-null  object
 7   CustomerKey    298246 non-null  int64
 8   Education      29797 non-null   object
 9   Name           29797 non-null   object
 10  Net_Price      298246 non-null  float64
 11  Occupation     29797 non-null   object
 12  OrderDate      298246 non-null  object
 13  Product_Name   298246 non-null  object
 14  ProductKey     298246 non-null  int64
 15  Quantity       298246 non-null  int64
 16  State          298246 non-null  object
 17  Subcategory    298246 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 41.0+ MB

In [6]:
df.isnull().sum()/len(df) *100

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 8, Finished, Available, Finished, False)

Brand             0.000000
Category          0.000000
City              0.000000
Color             0.000000
Continent         0.000000
CountryRegion     0.000000
Customer_Code     0.000000
CustomerKey       0.000000
Education        90.009254
Name             90.009254
Net_Price         0.000000
Occupation       90.009254
OrderDate         0.000000
Product_Name      0.000000
ProductKey        0.000000
Quantity          0.000000
State             0.000000
Subcategory       0.000000
dtype: float64

In [7]:
df.duplicated().sum()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 9, Finished, Available, Finished, False)

218008

In [8]:
df.drop_duplicates(inplace=True)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 10, Finished, Available, Finished, False)

In [9]:
df.info()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 11, Finished, Available, Finished, False)

<class 'pandas.core.frame.DataFrame'>
Index: 80238 entries, 0 to 298245
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Brand          80238 non-null  object
 1   Category       80238 non-null  object
 2   City           80238 non-null  object
 3   Color          80238 non-null  object
 4   Continent      80238 non-null  object
 5   CountryRegion  80238 non-null  object
 6   Customer_Code  80238 non-null  object
 7   CustomerKey    80238 non-null  int64
 8   Education      29797 non-null  object
 9   Name           29797 non-null  object
 10  Net_Price      80238 non-null  float64
 11  Occupation     29797 non-null  object
 12  OrderDate      80238 non-null  object
 13  Product_Name   80238 non-null  object
 14  ProductKey     80238 non-null  int64
 15  Quantity       80238 non-null  int64
 16  State          80238 non-null  object
 17  Subcategory    80238 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 11.6+ MB

In [10]:
df.shape

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 12, Finished, Available, Finished, False)

(80238, 18)

In [11]:
df.isnull().sum()/len(df) *100

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 13, Finished, Available, Finished, False)

Brand             0.000000
Category          0.000000
City              0.000000
Color             0.000000
Continent         0.000000
CountryRegion     0.000000
Customer_Code     0.000000
CustomerKey       0.000000
Education        62.864229
Name             62.864229
Net_Price         0.000000
Occupation       62.864229
OrderDate         0.000000
Product_Name      0.000000
ProductKey        0.000000
Quantity          0.000000
State             0.000000
Subcategory       0.000000
dtype: float64

In [12]:
df['OrderDate']=pd.to_datetime(df['OrderDate'],errors="coerce")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 14, Finished, Available, Finished, False)

In [13]:
df.shape

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 15, Finished, Available, Finished, False)

(80238, 18)

In [14]:
round(df.describe(),1)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 16, Finished, Available, Finished, False)

,CustomerKey,Net_Price,OrderDate,ProductKey,Quantity
count,80238.0,80238.0,80238,80238.0,80238.0
mean,15505.7,264.6,2008-12-20 13:37:32.389142528,1329.1,2.0
min,13.0,0.8,2008-01-01 00:00:00,1.0,1.0
25%,12876.0,27.0,2008-06-17 00:00:00,709.0,1.0
50%,18857.0,117.0,2008-11-25 00:00:00,1614.0,2.0
75%,18973.0,300.0,2009-06-19 00:00:00,1800.0,3.0
max,19143.0,3200.0,2009-12-31 00:00:00,2517.0,4.0
std,5516.7,415.6,NaN,699.1,1.2

In [15]:
df.describe(include="O")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 17, Finished, Available, Finished, False)

,Brand,Category,City,Color,Continent,CountryRegion,Customer_Code,Education,Name,Occupation,Product_Name,State,Subcategory
count,80238,80238,80238,80238,80238,80238,80238,29797,29797,29797,80238,80238,80238
unique,11,8,305,32,3,3,8868,5,8584,5,2495,41,32
top,Contoso,Games and Toys,Hamburg,Boxed Games,North America,United States,CS623,Partial College,"Edwards, Isaiah",Skilled Manual,MGS Hand Games for Office worker L299 Black,California,Boxed Games
freq,18560,21182,1957,11620,60756,60756,1487,8071,16,8002,530,19202,11620

# Checking Data Quality

In [16]:

df['Brand'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 18, Finished, Available, Finished, False)

Brand
Contoso                 18560
Tailspin Toys           16260
Southridge Video         9105
Litware                  7602
Fabrikam                 6337
Proseware                5743
Adventure Works          4553
Wide World Importers     4387
The Phone Company        3000
A. Datum                 2991
Northwind Traders        1700
Name: count, dtype: int64

In [17]:

print(df['City'].value_counts().to_string())

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 19, Finished, Available, Finished, False)

City
Hamburg              1957
Berlin               1935
Dresden              1632
Stuttgart            1441
Munich               1386
Chula Vista           991
Koln                  980
Beijing               896
Bellflower            860
Coronado              803
Bellingham            803
Burien                792
Worcester             768
Frankfurt             749
Milwaukie             748
West Covina           721
Guangzhou             706
Berkeley              705
Redmond               704
Beaverton             680
Novato                678
Woodburn              674
Newport Beach         672
Long Beach            663
Shanghai              642
Mill Valley           635
Lake Oswego           620
Concord               600
Beverly Hills         560
Spring Valley         559
Salem                 544
Hong Kong             543
Burbank               540
San Diego             536
San Gabriel           535
Seattle               534
Santa Cruz            504
La Jolla              502
Urumqi                500
Burlingame            496
Torrance              480
Paderborn             478
Bremerton             466
Los Angeles           457
Columbus              447
Colma                 436
Woodland Hills        435
Tacoma                433
Everett               410
Walla Walla           402
Kirkland              398
El Cajon              394
Casper                390
Yakima                390
Bradenton             384
Cedar City            375
Glendale              362
Sedro Woolley         358
Carson                357
Spokane               356
Syracuse              345
Chicago               333
Citrus Heights        332
New Brunswick         331
Baytown               326
Oregon                316
Solingen              315
Lemon Grove           314
Kassel                312
Darmstadt             312
Bonn                  311
Saarlouis             306
San Francisco         300
Winchester            298
Downey                297
Lebanon               295
Buffalo               294
Clackamas             289
Erlangen              287
Werne                 285
Lincoln Acres         283
Grossmont             282
Annapolis             282
Bottrop               280
Leominster            278
Ingolstadt            274
Naples                274
Beaumont              274
Hof                   271
Vineland              271
Daly City             269
Charleston            266
San Carlos            264
Albany                263
Olympia               261
East Orange           260
Issaquah              260
Pittsfield            257
Bayonne               254
National City         253
Sunnyside             253
Lynnwood              252
Provincetown          251
Madison               251
Santa Monica          250
Puyallup              250
Palo Alto             248
Marysville            247
Charlottesville       246
Virginia Beach        246
Lakewood              246
Corvallis             245
Hillsboro             245
Oregon City           242
Neunkirchen           241
Imperial Beach        241
Bangor                241
Houston               238
Central Valley        237
Edmonds               235
Austin                232
Englewood             228
Renton                227
Kiel                  225
Castle Rock           222
Redwood City          222
Wheat Ridge           221
Fremont               220
Marshall              219
La Porte              218
East Troy             216
Aurora                215
Fredericksburg        212
Round Rock            211
Darien                209
Jersey City           209
Oakland               208
Boulder               208
Port Washington       206
Holyoke               200
Norfolk               199
Cheektowaga           198
Portland              198
College Station       198
Miami                 196
Hartford              196
New Haven             193
Edgerton              188
Alexandria            187
Passaic               187
Sebring               186
Arlington             186
Barstow               184
Hingham               183
Hackensack            183
Denver                183
Green Bay             183
W. Linn               182
Port Orchard          182
Mühlheim am Main      181
Attleboro             181
Anchorage             180
Milliken              179
Grand Junction        178
Fond du Lac           178
Lewisville            177
Brunswick             176
Dallas                176
Trenton               176
Cape May              175
Kennewick             174
Framingham            173
Falmouth              172
Thornton              172
Longview              171
Cheney                171
Loveland              169
Hanover               168
Haverhill             168
Salzgitter            168
Granger               168
Atlantic City         165
Fort Lauderdale       165
Veradale              164
Littleton             164
Racine                163
Offenbach am Main     160
Berthoud              159
Grand Prairie         159
Cle Elum              159
Lewiston              159
Grevenbroich          159
Leipzig               159
Pasadena              158
San Antonio           157
Fall City             156
Tampa                 156
Lowell                155
Dusseldorf            154
Ballard               154
Essen                 153
Russellville          153
Manitowoc             152
Denton                150
Rochester             150
North Bend            149
Eilenburg             149
Munster               149
Sulzbach Taunus       149
Sheboygan             149
Baltimore             148
Saarbrücken           147
Waterbury             146
Martinsville          146
Poing                 146
New York              144
New Bedford           144
Parker                144
Minden                142
Sedalia               140
Howard                138
Roanoke               137
Chandler              137
Milwaukee             133
Fort Atkinson         132
Shreveport            131
Quincy                130
Tallahassee           129
Camarillo             128
Germantown            127
Hoboken               127
Bell Gardens          123
Paterson              123
Midland               122
Toppenish             122
Burlington            121
New Castle            120
Parkville             120
South Portland        115
Richardson            115
Snoqualmie            114
Jacksonville          114
Nantucket             113
Morristown            112
Newark                111
Lakeland              111
New London            110
Lynn                  110
Desoto                109
Lafayette             109
Bar Harbor            105
Ithaca                104
Orono                 103
Key West              102
Wapato                101
Oswego                100
Greenville             94
Spring                 91
Plano                  87
Appleton               85
Brooklyn               80
Orange                 80
Waukesha               78
Poestenkill            78
Humble                 75
Northampton            74
Ridgely                73
Montclair              66
Stoughton              66
Fort Worth             62
Somerville             61
Plattsburgh            54
Boston                 54
Texas City             51
Oshkosh                50
Old Saybrook           47
Orlando                46
Menasha                45
Canoga Park            41
Bethesda               40
Georgetown             33
Greeley                27
City Of Commerce       15
Carol Stream           14
Cincinnati             14
Clay                   14
Clifton                13
Cape Canaveral         10
Bluffton                8
Cheyenne                7
Elmira                  7
Charlotte               5
Bellevue                5
Branch                  4
Cedar Park              3
Bothell                 3
Clearwater              3
Campbellsville          3
Byron                   1
Bountiful               1
Billings                1
Chantilly               1
Cerritos                1
Carrollton              1
Braintree               1

In [18]:
df['Color'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 20, Finished, Available, Finished, False)

Color
Boxed Games                         11620
Download Games                       9562
Home Theater System                  4699
Computers Accessories                4480
Lamps                                3910
Washers & Dryers                     2941
Camcorders                           2507
Microwaves                           2406
Digital Cameras                      2303
Digital SLR Cameras                  2282
Printers, Scanners & Fax             2280
Projectors & Screens                 2277
Home & Office Phones                 2075
Refrigerators                        1982
Monitors                             1969
Smart phones & PDAs                  1934
Movie DVD                            1930
Fans                                 1859
Laptops                              1808
Coffee Machines                      1611
Cameras & Camcorders Accessories     1602
Air Conditioners                     1425
Bluetooth Headphones                 1369
MP4&MP3                              1293
Touch Screen Phones                  1272
Desktops                             1268
Car Video                            1227
Cell phones Accessories              1090
Televisions                          1068
Water Heaters                         738
VCD & DVD                             736
Recording Pen                         715
Name: count, dtype: int64

In [19]:

df['Subcategory'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 21, Finished, Available, Finished, False)

Subcategory
Boxed Games                         11620
Download Games                       9562
Home Theater System                  4699
Computers Accessories                4480
Lamps                                3910
Washers & Dryers                     2941
Camcorders                           2507
Microwaves                           2406
Digital Cameras                      2303
Digital SLR Cameras                  2282
Printers, Scanners & Fax             2280
Projectors & Screens                 2277
Home & Office Phones                 2075
Refrigerators                        1982
Monitors                             1969
Smart phones & PDAs                  1934
Movie DVD                            1930
Fans                                 1859
Laptops                              1808
Coffee Machines                      1611
Cameras & Camcorders Accessories     1602
Air Conditioners                     1425
Bluetooth Headphones                 1369
MP4&MP3                              1293
Touch Screen Phones                  1272
Desktops                             1268
Car Video                            1227
Cell phones Accessories              1090
Televisions                          1068
Water Heaters                         738
VCD & DVD                             736
Recording Pen                         715
Name: count, dtype: int64

In [20]:
# Color and Subcategory columns are identical so I have to drop Color
(df['Color'] == df['Subcategory']).all()

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 22, Finished, Available, Finished, False)

True

In [21]:
df.drop('Color', axis=1, inplace=True)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 23, Finished, Available, Finished, False)

In [22]:
df.shape

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 24, Finished, Available, Finished, False)

(80238, 17)

In [23]:

df['Continent'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 25, Finished, Available, Finished, False)

Continent
North America    60756
Europe           16195
Asia              3287
Name: count, dtype: int64

In [24]:

df['CountryRegion'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 26, Finished, Available, Finished, False)

CountryRegion
United States    60756
Germany          16195
China             3287
Name: count, dtype: int64

In [25]:
df.columns

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 27, Finished, Available, Finished, False)

Index(['Brand', 'Category', 'City', 'Continent', 'CountryRegion',
       'Customer_Code', 'CustomerKey', 'Education', 'Name', 'Net_Price',
       'Occupation', 'OrderDate', 'Product_Name', 'ProductKey', 'Quantity',
       'State', 'Subcategory'],
      dtype='object')

In [26]:


df['Education'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 28, Finished, Available, Finished, False)

Education
Partial College        8071
Bachelors              7124
High School            6541
Graduate Degree        4942
Partial High School    3119
Name: count, dtype: int64

In [27]:


df['Occupation'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 29, Finished, Available, Finished, False)

Occupation
Skilled Manual    8002
Professional      6835
Clerical          5336
Management        5267
Manual            4357
Name: count, dtype: int64

In [28]:

df['State'].value_counts().sort_values(ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 30, Finished, Available, Finished, False)

State
California                19202
Washington                 9853
Texas                      4750
Oregon                     4717
North Rhine-Westphalia     3505
Massachusetts              3473
Colorado                   2838
New Jersey                 2763
Wisconsin                  2712
Bavaria                    2364
New York                   2068
Hamburg                    1957
Saxony                     1940
Berlin                     1935
Florida                    1876
Hesse                      1714
Virginia                   1672
Baden-Wuerttemberg         1441
Maryland                    928
Connecticut                 901
Beijing                     896
Maine                       723
GuangDong                   706
Shanghai                    642
Saar                        602
Hong Kong                   543
Lower Saxony                512
Xinjiang                    500
Wyoming                     397
Utah                        376
South Carolina              368
Illinois                    347
Ohio                        301
Schleswig-Holstein          225
Alaska                      180
Georgia                     161
Arizona                     137
North Carolina                5
Minnesota                     4
Kentucky                      3
Montana                       1
Name: count, dtype: int64

In [29]:


print(df['Product_Name'].value_counts().to_string())

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 31, Finished, Available, Finished, False)

Product_Name
MGS Hand Games for Office worker L299 Black                                            530
MGS Hand Games women M400 Silver                                                       504
MGS Hand Games for Office worker L299 Silver                                           502
MGS Hand Games for kids E300 Black                                                     491
SV Hand Games men M30 Yellow                                                           456
MGS Hand Games for 12-16 boys E600 Red                                                 429
MGS Hand Games for Office worker L299 Yellow                                           428
MGS Hand Games women M400 Red                                                          415
SV Hand Games for 12-16 boys E60 Red                                                   372
MGS Hand Games for 12-16 boys E600 Silver                                              371
SV Hand Games women M40 Silver                                                         365
MGS Hand Games women M400 Yellow                                                       341
MGS Hand Games for Office worker L299 Red                                              339
SV Hand Games for students E40 Red                                                     322
SV Hand Games for kids E30 Yellow                                                      306
MGS Hand Games for kids E300 Silver                                                    277
SV Hand Games for kids E30 Silver                                                      266
SV Hand Games for Office worker L28 Yellow                                             254
MGS Hand Games women M400 Black                                                        251
SV Hand Games for students E40 Silver                                                  235
SV Hand Games for kids E30 Red                                                         231
MGS Hand Games for 12-16 boys E600 Black                                               231
SV Hand Games for 12-16 boys E60 Black                                                 229
SV Hand Games women M40 Yellow                                                         224
MGS Hand Games for students E400 Silver                                                216
MGS Hand Games for kids E300 Red                                                       214
SV Hand Games for Office worker L28 Black                                              214
SV Hand Games for students E40 Yellow                                                  207
MGS Hand Games for kids E300 Yellow                                                    196
SV Hand Games women M40 Red                                                            195
SV Hand Games women M40 Black                                                          191
MGS Hand Games for students E400 Yellow                                                176
MGS MechWarrior 4: Vengeance 2009 E175                                                 174
MGS Hand Games for students E400 Black                                                 169
SV Hand Games for students E40 Black                                                   164
MGS Hand Games for students E400 Red                                                   159
SV Hand Games for 12-16 boys E60 Yellow                                                158
MGS Hand Games for 12-16 boys E600 Yellow                                              150
SV Hand Games men M30 Silver                                                           146
MGS MechWarrior 4 Mach Packs X100                                                      143
SV Hand Games men M30 Black                                                            142
MGS MechWarrior 4: Knight E121                                                         141
MGS Age of Empires II Gold Edition E122                                                138
MGS Hand Games men M300 Silver                                                         133
MGS Halo: Combat Evolved2009 E149                                                      130
MGS Age of Empires III: The Asian Dynasties E106                                       125
MGS Age of Empires II: The Conquerors Expansion 2009 E178                              123
MGS Flight Simulator X 2008 E133                                                       123
MGS Freelancer 2009 E153                                                               120
MGS Shadow-run 2008 E131                                                               120
MGS Dungeon Siege: Legends of Aranna M330                                              120
MGS Age of Mythology: Gold Edition M310                                                119
MGS Zoo Tycoon Marine Mania E120                                                       118
MGS Fable: The Lost Chapters2008 E140                                                  118
MGS Age of Empires III 2008 E139                                                       118
MGS MechCollection E116                                                                116
MGS Combat Flight Simulator 3 E119                                                     115
MGS Age of Empires II: The Age of Kings 2009 E180                                      115
MGS Train Simulator 2009 E174                                                          114
MGS Gears of War M170                                                                  113
MGS Halo 2 for Windows Vista M220                                                      112
MGS Age of Empires III: The War Chiefs 2007 E132                                       110
MGS Racing Madness 2009 E169                                                           107
WWI 4GB Video Recording Pen X200 Black                                                 107
MGS Age of Empires III: The War Chiefs M240                                            106
MGS Gears of War 2008 M450                                                             106
MGS Rise of Nations: Gold Edition 2009 E143                                            106
MGS Bicycle Casino Games2009 E167                                                      105
MGS Bicycle Board Games2009 E165                                                       105
MGS Zoo Tycoon 2: African Adventure 2008 E136                                          105
MGS Halo: Combat Evolved E109                                                          105
MGS MechWarrior 4: Mercenaries E117                                                    105
MGS Age of Mythology: The Titans Expansion M350                                        105
MGS Collector's M160                                                                   104
WWI 2GB Pulse Smart pen M100 Blue                                                      104
MGS Bicycle Card Games2009 E166                                                        103
MGS Flight Simulator 2002 M360                                                         102
MGS Zoo Tycoon 2: African Adventure M280                                               100
SV Hand Games for kids E30 Black                                                        99
MGS RalliSport Challenge E115                                                           99
Contoso Home Theater System 5.1 Channel M1520 White                                     97
MGS Return of Arcade Anniversary Edition M390                                           97
MGS Hand Games men M300 Black                                                           97
Contoso Home Theater System 4.1 Channel M1410 Black                                     96
MGS Train Simulator E124                                                                95
MGS Age of Empires II Gold Edition2009 E172                                             95
Contoso Home Theater System 7.1 Channel M1700 Black                                     95
MGS Dungeon Siege: Legends of Aranna 2009 E146                                          93
MGS MechWarrior 4: Vengeance X800                                                       93
Contoso Home Theater System 4.1 Channel M1420 White                                     93
MGS Rise of Nations2009 E152                                                            92
MGS Racing Madness 2 M370                                                               92
Contoso Washer & Dryer 15.5in E155 Blue                                                 91
MGS Zoo Tycoon2009 E170                                                                 91
Contoso Home Theater System 4.1 Channel M1400 Silver                                    90
Litware Home Theater System 5.1 Channel M516 Black                                      90
MGS Age of Mythology: Gold Edition 2009 E144                                            90
MGS Flight Simulator 2000 M410                                                          89
MGS Flight Simulator 2004: A Century of Flight E111                                     89
MGS Halo 2 for Windows Vista 2009 E130                                                  88
Contoso 8GB Super-Slim MP3/Video Player M800 White                                      87
Contoso Home Theater System 5.1 Channel M1530 Black                                     86
MGS Rise of Nations: Thrones and Patriots2009 E145                                      86
MGS Age of Empires II: The Conquerors Expansion E125                                    86
MGS Return of Arcade Anniversary Edition 2009 E176                                      86
Litware Washer & Dryer 15.5in E150 White                                                85
MGS Zoo Tycoon 2: Zookeeper Collection M260                                             85
Contoso 8GB Super-Slim MP3/Video Player M800 Pink                                       84
MGS Freelancer E113                                                                     84
MGS Age of Mythology 2009 E158                                                          84
Litware Washer & Dryer 21in E214 Green                                                  84
MGS Zoo Tycoon Complete Collection E110                                                 83
Litware Home Theater System 2.1 Channel E212 Brown                                      83
MGS Kings & Myths: The Age Collection2009 E147                                          83
MGS Bicycle Board Games X500                                                            82
MGS MechCommander 2009 E173                                                             82
MGS Zoo Tycoon Dinosaur Digs2009 E162                                                   81
MGS Age of Empires III: The Asian Dynasties 2008 E126                                   81
MGS Rise of Nations E112                                                                81
MGS Flight Simulator X M250                                                             80
MGS Fable: The Lost Chapters E107                                                       80
MGS Combat Flight Simulator 2009 E159                                                   79
MGS Dungeon 2007 E141                                                                   78
MGS Shadow-run M230                                                                     77
WWI 2GB Pulse Smart pen M100 Black                                                      77
Litware Washer & Dryer 15.5in E150 Green                                                76
MGS Zoo Tycoon Marine Mania 2009 E160                                                   76
MGS Classic Flight Collection2009 E164                                                  75
MGS Flight Simulator 2009: A Century of Flight E151                                     75
Litware Home Theater System 5.1 Channel M516 Silver                                     75
SV Hand Games men M30 Red                                                               75
NT Washer & Dryer 15.5in E1550 Green                                                    75
MGS King& Myths: The Age Collection M340                                                75
NT Washer & Dryer 24in M2400 Blue                                                       75
Litware Home Theater System 5.1 Channel M515 Silver                                     74
Contoso Home Theater System 4.1 Channel M1400 Brown                                     74
Contoso Home Theater System 5.1 Channel M1500 White                                     73
NT Wireless Bluetooth Stereo Headphones M402 Green                                      73
Contoso Home Theater System 2.1 Channel E1200 Silver                                    73
Contoso Home Theater System 2.1 Channel M1230 White                                     72
Contoso Washer & Dryer 25.5in M255 White                                                72
Contoso Home Theater System 2.1 Channel M1210 Brown                                     72
MGS MechCommander 2 E123                                                                72
SV Hand Games for Office worker L28 Red                                                 71
MGS Hand Games men M300 Red                                                             71
MGS Age of Empires III: The Asian Dynasties M180                                        71
MGS Zoo Tycoon Dinosaur Digs X200                                                       71
MGS MechWarrior4: Mercenaries2009 E157                                                  71
Litware Home Theater System 7.1 Channel M710 Brown                                      70
MGS Age of Empires III: The Asian Dynasties 2009 E127                                   69
MGS Age of Empires III: The Asian Dynasties M190                                        69
Contoso Home Theater System 5.1 Channel M1540 Black                                     69
Contoso Bluetooth Active Headphones L15 Black                                           69
NT Washer & Dryer 27in L2700 Blue                                                       69
MGS Classic Flight Collection X400                                                      68
MGS Bicycle Card Games X600                                                             68
Contoso Washer & Dryer 24in M240 Pink                                                   67
MGS Rise of Nations: Gold Edition M300                                                  67
Contoso Washer & Dryer 15.5in E155 Red                                                  67
Litware 17'' Oscillating Pedestal Fan M125 Yellow                                       67
Contoso Washer & Dryer 15.5in E155 Green                                                66
Litware Home Theater System 2.1 Channel E211 Brown                                      66
MGS Impossible Creatures2009 E154                                                       66
Litware Home Theater System 2.1 Channel E212 Black                                      65
Litware Home Theater System 5.1 Channel M510 Brown                                      65
Contoso Home Theater System 5.1 Channel M1500 Silver                                    65
Contoso Original K1m Li-Ion Standard Battery E170 Black                                 64
Contoso Washer & Dryer 25.5in M255 Pink                                                 64
Contoso Washer & Dryer 15.5in E155 Silver                                               64
Litware Home Theater System 4.1 Channel M410 Silver                                     64
MGS Flight Simulator X Acceleration Expansion Pack 2009 E128                            64
Litware Washer & Dryer 21in E214 White                                                  63
MGS Zoo Tycoon 2: End range Species Expansion Pack E105                                 63
SV Car Video LCD9.2W X9281 Black                                                        63
Contoso 8GB MP3 Player new model M820 Blue                                              63
Contoso Home Theater System 5.1 Channel M1520 Black                                     63
Contoso Touch Stylus Pen E150 Red                                                       62
Litware Washer & Dryer 21in E214 Blue                                                   62
Proseware LCD22 M2000 White                                                             62
Contoso Home Theater System 5.1 Channel M1500 Black                                     61
MGS Zoo Tycoon 2: Extinct Animals 2008 E129                                             61
Contoso Home Theater System 4.1 Channel M1410 Silver                                    61
MGS Age of Empires 2008new M420                                                         61
MGS Rise of Nations: Rise of Legends 2008 E137                                          60
MGS Zoo Tycoon 2008 E142                                                                60
Contoso Home Theater System 4.1 Channel M1420 Black                                     60
Cigarette Lighter Adapter for Contoso Phones E110 Black                                 60
MGS Age of Empires, 2009 E182                                                           60
Litware Home Theater System 5.1 Channel M510 Silver                                     59
Litware Home Theater System 2.1 Channel E210 Brown                                      59
Contoso Home Theater System 2.1 Channel E1220 Brown                                     58
Contoso Home Theater System 5.1 Channel M1510 White                                     58
Contoso 4GB Portable MP3 Player M450 Yellow                                             58
MGS Age of Mythology: The Titans Expansion 2009 E148                                    58
NT Washer & Dryer 15.5in E1550 Blue                                                     58
Adventure Works LCD20 M210 White                                                        58
Contoso Home Theater System 2.1 Channel M1210 Black                                     58
Litware Home Theater System 5.1 Channel M513 Black                                      57
Contoso Home Theater System 5.1 Channel M1510 Brown                                     57
Litware Washer & Dryer 25.5in M350 Blue                                                 57
MGS Dungeon Siege X300                                                                  57
MGS Zoo Tycoon 2: Marine Mania Expansion Pack M270                                      57
Litware Wall Lamp E3015 Grey                                                            57
MGS Zoo Tycoon2: Marine Mania Expansion Pack 2008 E135                                  56
SV DVD Recorder L200 Black                                                              56
Contoso Washer & Dryer 24in M240 White                                                  56
SV 16xDVD M360 Black                                                                    56
A. Datum Compact Digital Camera M200 Green                                              56
Contoso Lens Cap Keeper E314 Pink                                                       56
Litware Home Theater System 4.1 Channel M413 Brown                                      56
Litware Home Theater System 2.1 Channel E210 Silver                                     56
NT Washer & Dryer 21in E2100 Green                                                      56
MGS Bicycle Casino Games X700                                                           56
Contoso Home Theater System 2.1 Channel E1200 Black                                     55
Contoso Home Theater System 5.1 Channel M1520 Brown                                     55
Proseware Laptop8.9 E089 Black                                                          55
WWI Wireless Bluetooth Stereo Headphones M270 White                                     55
Litware Home Theater System 5.1 Channel M515 Brown                                      55
Litware Home Theater System 4.1 Channel M410 Black                                      55

In [30]:
# Removing extra spaces from the attributes of each column

df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 32, Finished, Available, Finished, False)

In [31]:
# Removing  CS to all Customer Codes
df['Customer_Code'] = df['Customer_Code'].str.replace('CS', '')

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 33, Finished, Available, Finished, False)

In [32]:
df[df['Customer_Code'].str.startswith('CS')]

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 34, Finished, Available, Finished, False)

Empty DataFrame
Columns: [Brand, Category, City, Continent, CountryRegion, Customer_Code, CustomerKey, Education, Name, Net_Price, Occupation, OrderDate, Product_Name, ProductKey, Quantity, State, Subcategory]
Index: []

In [33]:
df['Customer_Code'] = df['Customer_Code'].astype(int)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 35, Finished, Available, Finished, False)

In [34]:
df.dtypes

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 36, Finished, Available, Finished, False)

Brand                    object
Category                 object
City                     object
Continent                object
CountryRegion            object
Customer_Code             int64
CustomerKey               int64
Education                object
Name                     object
Net_Price               float64
Occupation               object
OrderDate        datetime64[ns]
Product_Name             object
ProductKey                int64
Quantity                  int64
State                    object
Subcategory              object
dtype: object

In [35]:
# Round Net Price to 2 decimals 
df["Net_Price"]=round(df["Net_Price"],2)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 37, Finished, Available, Finished, False)

# Filling Missing Data

In [36]:
df['Education'] = df['Education'].fillna("Unknown")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 38, Finished, Available, Finished, False)

In [37]:
df['Occupation'] = df['Occupation'].fillna("Unknown")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 39, Finished, Available, Finished, False)

In [39]:
# Filling the missing name with Customer_and his code for example Customer_1111

mask = df['Name'].isna()

df.loc[mask, 'Name'] = (
    'Customer_' +
    df.loc[mask, 'Customer_Code'].astype(str)
)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 42, Finished, Available, Finished, False)

In [52]:
df.groupby('Name')['TotalRevenue'].sum().reset_index().sort_values('TotalRevenue', ascending=False)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 55, Finished, Available, Finished, False)

                   Name  TotalRevenue
1673       Customer_623    1023521.89
1639       Customer_555     898148.40
1678       Customer_636     810971.55
1653       Customer_586     756757.85
1704       Customer_744     700776.60
...                 ...           ...
4621      Martin, Eddie          5.39
7450  Stewart, Jeremiah          5.39
3648   James, Gabrielle          5.39
8796       Zheng, Louis          3.99
1359    Coleman, Morgan          3.99

[8843 rows x 2 columns]

# Feature Engineering

In [53]:
df['TotalRevenue'] = df['Net_Price'] * df['Quantity']

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 56, Finished, Available, Finished, False)

In [54]:
df.shape

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 57, Finished, Available, Finished, False)

(80238, 18)

# Saving the table in the silver Layer

In [55]:
df_spark_silver = spark.createDataFrame(df)

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 58, Finished, Available, Finished, False)

In [56]:
df_spark_silver.write.mode('overwrite').format("delta").saveAsTable("silver.sales")

StatementMeta(, 48b22c84-4e9e-4bc7-ad63-2e670ac45679, 59, Finished, Available, Finished, True)